#!/bin/bash
# Account
#SBATCH -A  hpc2n2023-018
#Set the Job name
#SBATCH --job-name=condo
# Set the names for the error and output files
# The job may take up to 2 hours to complete
#SBATCH --time=2:00:00
# Asking for 1 node
#SBATCH -c 1


module load binutils/2.38
module load GCCcore/11.3.0
module load XZ/5.2.5
module load  Python/3.10.4
module load GCC/11.3.0
module load CMake

python -m venv venv
source /home/k/klasm/store/KLAS/CONDORCET-NEW/venv/bin/activate

module load OpenMPI/4.1.4
module load   SciPy-bundle/2022.05


i=${SLURM_ARRAY_TASK_ID}



python ../python/parallel_search.py -n 7  \
       -cutoff 16  \
       -threshold 0 \
       -top_n 1000  \
       -rules "2N3" "2N1" "1N3" "3N1"  \
       -triple_id 6 \
       -core_id ${i} \
       -lib_path "/home/k/klasm/store/KLAS/CONDORCET-NEW/cdl" \
       -result_path "/home/k/klasm/store/KLAS/CONDORCET-NEW/cdl/results"

status=$?


if [ $status -ne 0 ]
then
    touch problem-$i
fi
date

echo "done"


